apiVersion: v1
kind: Service
metadata:
  name: {{ include "tmonitoring.fullname" . }}-client
  labels:
{{ include "tmonitoring.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "tmonitoring.name" . }}-client
    app.kubernetes.io/instance: {{ .Release.Name }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "tmonitoring.fullname" . }}-api
  labels:
{{ include "tmonitoring.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "tmonitoring.name" . }}-api
    app.kubernetes.io/instance: {{ .Release.Name }}
